baseURL = "https://vernetztesarbeiten.de"
languageCode = "de"
DefaultContentLanguage = "de"
title = "Martin Brink-Abeler - Berater f체r Digitalisierung und andere Ver채nderungen"
theme = "anatole"
publishDir = "docs/"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = """
Martin Brink-Abeler
"""
author = """Martin Brink-Abeler"""
copyright = """Martin Brink-Abeler 2021 - [Datenschutz und Impressum](/impressum)
"""
description = """
Beratung f체r Zusammenarbeit,
Digitalisierung und andere Ver채nderungen
"""
profilePicture = "images/profile.jpg"
keywords = "change mangagement, agile, agile coach,  organisationsentwicklung, coaching"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["docs"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
indexDateFormat = "02.01.2006"
listDateFormat = "02.01."
singleDateFormat = "02.01.2006"

# Read More links for truncated summaries
#readMore = true
postSectionName = "blog"
#fullPostContent = true

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/brinkabeler/"

[[params.socialIcons]]
icon = "fab fa-xing"
title = "Xing"
url = "https://www.xing.com/profile/Martin_BrinkAbeler"


# [[params.socialIcons]]
# icon = "fas fa-envelope"
# title = "e-mail"
# url = "mailto:mba@vernetztesarbeiten.de"

## Menu items

[menu]

  [[menu.main]]
  name = "Moin"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 500
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Kontakt"
  weight = 700
  identifier = "kontakt"
  url = "/#kontakt-aufnehmen"

